volumes:
  mysql-data:

networks:
  spring-boot-mysql-network:

services:

  mysqldb:
    image: mysql:lts
    command: --mysql-native-password=on
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 3s
      timeout: 30s


  invoksa:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/invoksa_db
      - SPRING_DATASOURCE_USERNAME=invoksa_user
      - SPRING_DATASOURCE_PASSWORD=MFPZBbT03Jxd2f8Oun7LytAlsB5a5KspaK+wzJcuAjw=
      - MAIL_USERNAME=abdelmalikkouadjo@gmail.com
      - MAIL_PASSWORD=xgwsdihnqldpljht
      - OPENAI_API_KEY=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
      - APP_SECRET_KEY=1293801802989812384238401820394812394
    networks:
      - spring-boot-mysql-network



