spring:
  application:
    name: invoksa_springboot

  datasource:
    url: {SPRING_DATASOURCE_URL}
    username: {SPRING_DATASOURCE_USERNAME}
    password: {SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: abdelmalikkouadjo@gmail.com
    password: xgwsdihnqldpljht
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: 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
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0
          maxTokens: 1024
          proxy-tool-calls: false

app:
  secret-key: 1293801802989812384238401820394812394
  expiration-time: 2592000000